# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f0a017422aa93247227e994c31385f90324600983af8b282b54c3659886c4d04d1c73a0ebb9fbaf2517af0c9d38a0d9314c7be7d1cc8bbb10b84ffd679e622d

test:
  secret_key_base: 55d53fafa218f5453db36c7b910c939afa5ca6ceff4fbc8b7bac22de0573208e2b2d1b7651463715bba7bbe925e167ee423762e87d0300de49b549f31b0b1040

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
